### ISSUE TITLE
Unable to run 'reflect' example

### ISSUE THREAD

**Issue by wayeast** [webrtc-rs/examples#11]
Hi,

I just cloned this repository and am trying to get the reflect example running.  Following the steps in the README, I have navigated in my browser to the linked `jsfiddle` page, clicked to allow it to use my microphone and camera, copied the browser session token, and echoed it to `target/debug/examples/reflect`.  This last step results in a message "one of audio or video must be enabled."  How can I get this example running?

OS: Arch (Manjaro)
Browser: Firefox 100.0; Chrome 101.0.4951.64
Rust: 1.60.0

**Comment by rainliu** [comment]
target/debug/examples/reflect -a -v

**Comment by wayeast** [comment]
Thank you @rainliu for the tip.  Appears to be working now :+1:
