### ISSUE TITLE
pasting offers results in `Error: EOF while parsing a string at line 1 column 3071`

### ISSUE THREAD

**Issue by scottlamb** [webrtc-rs/examples#16]
Looks like most/all of the examples work by pasting a base64 string from a [jsfiddle](https://jsfiddle.net/9s10amwL/) to the program via this snippet:

```rust
    // Wait for the offer to be pasted
    let line = signal::must_read_stdin()?;
    let desc_data = signal::decode(line.as_str())?;
    let offer = serde_json::from_str::<RTCSessionDescription>(&desc_data)?;
```

On my browser (Chrome 103.0.5060.114 on macOS), the base64 string is 11,308 bytes. This is over the 4,096-byte limit for line length for "canonical mode" terminal input on Linux (see e.g. [this blog post](http://blog.chaitanya.im/4096-limit)), so pasting doesn't work right:

```
$ cargo run --example play-from-disk-h264 -- --video $HOME/out.mp4
...paste here...
Error: EOF while parsing a string at line 1 column 3071
```

Note (4096 - 1 [for `\n`]) * 3/4 rounds down to 3071.

If you run it through `strace -oout -s8192`, you can see the `read(0, "...4095 characters...\n", 8192) = 4096` indicating that the kernel silently truncated the line.

Ideas:

*   use `rustyline` or similar to take the terminal out of "canonical mode" before reading the input, to get rid of the 4,096-byte limitation. Note that pasting into e.g. `vim` works fine because they use raw mode.
*   try to get the string be under 4,096 bytes by gzipping it or something
*   have the examples start a webserver so you can navigate to their URL and have the browser send the offer directly to the webserver, rather than pasting it back and forth.

**Comment by k0nserv** [comment]
We have migrated this crate to the monorepo([webrtc-rs/webrtc](https://github.com/webrtc-rs/webrtc/)) please re-open this issue over there.
